package Model;
// Generated 29-11-2017 13:44:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int rut;
     private String nombreEmpresa;
     private String direccionEmpresa;
     private String nombreComprador;
     private int opcionPago;
     private int opcionRetiro;
     private Set compras = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int rut, String nombreEmpresa, String direccionEmpresa, String nombreComprador, int opcionPago, int opcionRetiro) {
        this.rut = rut;
        this.nombreEmpresa = nombreEmpresa;
        this.direccionEmpresa = direccionEmpresa;
        this.nombreComprador = nombreComprador;
        this.opcionPago = opcionPago;
        this.opcionRetiro = opcionRetiro;
    }
    public Cliente(int rut, String nombreEmpresa, String direccionEmpresa, String nombreComprador, int opcionPago, int opcionRetiro, Set compras) {
       this.rut = rut;
       this.nombreEmpresa = nombreEmpresa;
       this.direccionEmpresa = direccionEmpresa;
       this.nombreComprador = nombreComprador;
       this.opcionPago = opcionPago;
       this.opcionRetiro = opcionRetiro;
       this.compras = compras;
    }
   
    public int getRut() {
        return this.rut;
    }
    
    public void setRut(int rut) {
        this.rut = rut;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getDireccionEmpresa() {
        return this.direccionEmpresa;
    }
    
    public void setDireccionEmpresa(String direccionEmpresa) {
        this.direccionEmpresa = direccionEmpresa;
    }
    public String getNombreComprador() {
        return this.nombreComprador;
    }
    
    public void setNombreComprador(String nombreComprador) {
        this.nombreComprador = nombreComprador;
    }
    public int getOpcionPago() {
        return this.opcionPago;
    }
    
    public void setOpcionPago(int opcionPago) {
        this.opcionPago = opcionPago;
    }
    public int getOpcionRetiro() {
        return this.opcionRetiro;
    }
    
    public void setOpcionRetiro(int opcionRetiro) {
        this.opcionRetiro = opcionRetiro;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


