package Model;
// Generated 04-12-2017 12:25:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int rut;
     private String nombreEmpresa;
     private String direccionEmpresa;
     private Set compras = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int rut, String nombreEmpresa, String direccionEmpresa) {
        this.rut = rut;
        this.nombreEmpresa = nombreEmpresa;
        this.direccionEmpresa = direccionEmpresa;
    }
    public Cliente(int rut, String nombreEmpresa, String direccionEmpresa, Set compras) {
       this.rut = rut;
       this.nombreEmpresa = nombreEmpresa;
       this.direccionEmpresa = direccionEmpresa;
       this.compras = compras;
    }
   
    public int getRut() {
        return this.rut;
    }
    
    public void setRut(int rut) {
        this.rut = rut;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getDireccionEmpresa() {
        return this.direccionEmpresa;
    }
    
    public void setDireccionEmpresa(String direccionEmpresa) {
        this.direccionEmpresa = direccionEmpresa;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


