package Model;
// Generated 04-12-2017 12:25:46 by Hibernate Tools 4.3.1



/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Carretera carretera;
     private Cliente cliente;
     private int numeroPedido;
     private int cantidad;
     private int precioUnitario;
     private String nombreComprador;
     private int opcionPago;
     private int opcionRetiro;

    public Compra() {
    }

    public Compra(Carretera carretera, Cliente cliente, int numeroPedido, int cantidad, int precioUnitario, String nombreComprador, int opcionPago, int opcionRetiro) {
       this.carretera = carretera;
       this.cliente = cliente;
       this.numeroPedido = numeroPedido;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
       this.nombreComprador = nombreComprador;
       this.opcionPago = opcionPago;
       this.opcionRetiro = opcionRetiro;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Carretera getCarretera() {
        return this.carretera;
    }
    
    public void setCarretera(Carretera carretera) {
        this.carretera = carretera;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public int getNumeroPedido() {
        return this.numeroPedido;
    }
    
    public void setNumeroPedido(int numeroPedido) {
        this.numeroPedido = numeroPedido;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public int getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(int precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public String getNombreComprador() {
        return this.nombreComprador;
    }
    
    public void setNombreComprador(String nombreComprador) {
        this.nombreComprador = nombreComprador;
    }
    public int getOpcionPago() {
        return this.opcionPago;
    }
    
    public void setOpcionPago(int opcionPago) {
        this.opcionPago = opcionPago;
    }
    public int getOpcionRetiro() {
        return this.opcionRetiro;
    }
    
    public void setOpcionRetiro(int opcionRetiro) {
        this.opcionRetiro = opcionRetiro;
    }




}


